spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: f4kemailt3st@gmail.com
    password: wmlgajpmfuikdost
    properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true

